#!/usr/bin/env node
// Writes src/version.ts from package.json.
//
// The SDK sends `User-Agent: form4api-js/<version>` so the backend can attribute
// traffic to the JS SDK channel and answer "who is still on an old version"
// before a breaking change. That only works if the version is true.
//
// It was previously a hand-maintained constant with a comment asking whoever
// released to keep it in sync with package.json. It drifted: the constant said
// 1.1.3 while the published package was 1.2.0, so every request from the SDK
// misreported itself, and the one signal that would have revealed it — the
// admin client-versions view — showed nothing because the JS SDK has never
// appeared in production traffic at all.
//
// Generating it removes the coupling to anyone's memory. Run by `prebuild`, so a
// release physically cannot ship a stale version, and asserted by a test so a
// stale committed copy fails locally too.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const { version } = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

if (!/^\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(version)) {
  // The backend parses strictly: exactly three numeric segments, 1-3 digits
  // each. Anything else is stored as a null version, which silently removes
  // this release from the upgrade-notification list.
  console.error(
    `codegen/version.mjs: package.json version "${version}" is not major.minor.patch ` +
      `with 1-3 digits per segment. The backend would record it as an unknown version.`,
  );
  process.exit(1);
}

const out = `// GENERATED by codegen/version.mjs from package.json — do not edit.
// Run \`npm run codegen:version\` (or any build) to regenerate.
export const SDK_VERSION = ${JSON.stringify(version)};
`;

writeFileSync(join(root, "src", "version.ts"), out);
console.log(`src/version.ts <- ${version}`);
